version: '3.1'
services:

  wiremock:
    image: wiremock/wiremock:3.4.1
    command:
      - --local-response-templating
    ports:
      - "9091:8080"
    volumes:
      - ./wiremock:/home/wiremock
